# Generated by Django 4.1.5 on 2023-01-29 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main_page',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
