# Generated by Django 4.1.5 on 2023-02-03 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0002_alter_main_page_title'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='main_page',
            new_name='Game',
        ),
    ]
