# Generated by Django 4.1.5 on 2023-02-19 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0004_game_tag_alter_game_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='publisher',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
