# Generated by Django 4.1.5 on 2023-02-19 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0005_game_publisher'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='publisher',
            new_name='developer',
        ),
    ]
