# Generated by Django 4.1.7 on 2023-03-11 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0011_alter_comment_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('lowest_price', models.CharField(max_length=100)),
            ],
        ),
    ]
